name: WeChat MiniProgram Demo CI/CD
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  secrets: read 
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone submodule
        run: git submodule status

      - name: Install dependencies
        run: npm install

      - name: Run package script
        run: npm run init

      - name: Upload MiniProgram
        env:
          WX_PRIVATE_KEY: ${{ secrets.WX_PRIVATE_KEY }}
        run: |
          # 验证密钥是否为空
          if [ -z "$WX_PRIVATE_KEY" ]; then
            echo "❌ 错误: WX_PRIVATE_KEY 为空，请检查 GitHub Secrets 设置"
            exit 1
          fi
          mkdir -p ./build
          echo "$WX_PRIVATE_KEY" > ./build/key
          echo "$WX_PRIVATE_KEY" | xxd

