name: PR Lint Check

on:
  push:
    branches:
      - feat-pr-lint

concurrency:
  group: style-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
           miniprogram/**/*

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          node-version: 20

      - name: Web dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm install

      - name: Web style check
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm run lint
